### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by stevetoro** [RoyalRiek/prj-rev-bwfs-dasmoto#6]
https://github.com/RoyalRiek/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/Resources/style.css#L10-L16

You've got a lot of repetition here.

Move shared styles into a CSS rules with more general selectors. For example:

```css
* {
  font-family: Helvetica;
}

h2 {
  font-size: 32px;
  font-weight: bold;
  color: white;
}

#title-brush {
  background-color: mediumspringgreen;
}
```

You also should not apply the `font-weight: bold` style to every paragraph. The price should be bold, but not the regular paragraph. 

Keep in mind this approach to writing concise CSS so that you can make your code easy to maintain.
